### ISSUE TITLE
Histogram error related to non-monotonic binsize

### ISSUE THREAD

**Issue by sundarjhu** [JohannesBuchner/nway#9]
When using the "--mag DATA:MAG auto" option, the following error was encountered for one of the five magnitudes in my data:

Traceback (most recent call last):
  File "/Users/sundar/virtual_env/nway_env/bin//nway.py", line 338, in <module>
    bins, hist_sel, hist_all = magnitudeweights.adaptive_histograms(mag_all[mask_others], mag_sel[mask_sel])
  File "/Users/sundar/virtual_env/nway_env/lib/python3.7/site-packages/nwaylib/magnitudeweights.py", line 97, in adaptive_histograms
    hist_sel, bins = numpy.histogram(mag_sel, bins=x,    density=True)
  File "/Users/sundar/virtual_env/nway_env/lib/python3.7/site-packages/numpy/lib/histograms.py", line 710, in histogram
    bin_edges, uniform_bins = _get_bin_edges(a, bins, range, weights)
  File "/Users/sundar/virtual_env/nway_env/lib/python3.7/site-packages/numpy/lib/histograms.py", line 369, in _get_bin_edges
    '`bins` must increase monotonically, when an array')

Upon printing the variable x after line 93 in magnitudeweights.py, I discovered that, indeed, the last two elements in x were not in ascending order. I'm tracking down this issue in my data, but in the meantime I have fixed it by using the sort() method after line 93, before numpy.histogram() is called:
x.sort()

Cheers,
Sundar

**Comment by JohannesBuchner** [comment]
Hi Sundar,

thanks for spotting this. I made some changes, could you please test the latest version in this git repository (commit e463243)? You can run nway directly from the cloned repo (python nway.py) or by installing it.

Cheers,
Johannes

**Comment by JohannesBuchner** [comment]
This should be fixed in the latest version (4.1). If you can test and report back that would be appreciated.
